### ISSUE TITLE
` / tilde key wrong character 

### ISSUE THREAD

**Issue by ruiaraujo012** [tjsousa/altgr-weur-mac#3]
Hi,

I have followed the instructions to install this, all works great except the `/tilde key that put the character < and >, I have a Nuphy Air75, is this a issue or do I need to map the keys via Karabiner? 

Any help @tjsousa 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/16304685/187035233-9276bf8b-3b2e-494a-9c06-253eaf5402fa.png">

**Comment by tjsousa** [comment]
Hey @ruiaraujo012, thanks for reporting. For some reason this does not happen in my keyboard, I have to investigate further with a different keyboard and will get back to you.

**Comment by ruiaraujo012** [comment]
Thank you @tjsousa.

Some info that I found on the internet is the fact that my internal macbook keyboard layout it's PT-pt, and for some reason this appens. But I can't find any way to resolve that. What I'm doing right now is remap this keys via Karabiner, it isn't the easiest or the simplest way but this way I can use those keys for now.
